version: '3'
services:
  db:
    build: ./api/database 
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=SADatabase
    volumes:
      - ./api/database:/docker-entrypoint-initdb.d
  api:
    build: ./api
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app
    environment:
      FLASK_ENV: development
    depends_on:
      - db       
  dashboard:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - /usr/src/app    
    depends_on:
      - api
