version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      FLASK_ENV: development
  dashboard:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - /usr/src/app    
    depends_on:
      - backend
