version: '3'

services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app
    environment:
      FLASK_ENV: development
  db:
    build: ./api/database 
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=SADashboard
      - POSTGRES_PASSWORD=dashboard
      - POSTGRES_DB=SAData
    volumes:
      - ./api/database:/data      
  dashboard:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - /usr/src/app    
    depends_on:
      - api
