version: '3'

services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app
    environment:
      FLASK_ENV: development
  dashboard:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - /usr/src/app    
    depends_on:
      - api
