version: '3.3'

services:
  db:
    build: ./db
    container_name: postgres
    ports:
      - "5431:6666"
    environment:
      - POSTGRES_USER=SADashboard
      - POSTGRES_PASSWORD=dashboard
      - POSTGRES_DB=SAData
    volumes:
      - ./data:/data